sonar.projectKey=positivus
sonar.projectName=positivus
sonar.projectVersion=1.0

# Source files
sonar.sources=src
sonar.language=js
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# JS/TS specific
sonar.javascript.tsconfigPath=tsconfig.json
sonar.typescript.tsconfigPath=tsconfig.json

# Optional: ignore things
sonar.exclusions=node_modules/**,dist/**
