sonar.projectKey=positivus
sonar.projectName=positivus
sonar.sources=src
sonar.javascript.tsconfigPath=tsconfig.json
sonar.typescript.tsconfigPath=tsconfig.json
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/*.spec.js
sonar.javascript.exclusions=**/node_modules/**, **/*.d.ts
sonar.javascript.node.maxspace=1024
sonar.typescript.node.maxspace=1024
sonar.javascript.maxFileSize=400

