sonar.projectKey=positivus
sonar.projectName=positivus
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**
sonar.javascript.tsconfigPath=tsconfig.json
sonar.typescript.tsconfigPath=tsconfig.json
